version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=odoo
    volumes:
      - "../db_data/:/var/lib/postgresql/data"
      - "../db_backup/:/db_backup/"
  web:
    build: .
    volumes:
      - ".:/src"
    ports:
      - "8000:80"
      - "8069:8069"
    depends_on:
      - db
